name: CI
on:
    pull_request:
        branches:
            - main
jobs:
    Lint_and_Validate:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Check style guide
              run: npx awesome-lint
