name: Parse RSS

on:
  schedule:
  - cron: '0 */12 * * *'

  workflow_dispatch:

  pull_request:
    branches:
        - main

jobs:
    parse_rss:
        runs-on: ubuntu-latest
        env:
          CUSTOM_GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

            - uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - uses: actions/setup-python@v4
              with:
                python-version: '3.9'
                cache: 'pip' # caching pip dependencies

            - name: Parse latest episodes from RSS
              run:
                  cd .github/scripts &&
                  pip install -r requirements.txt &&
                  python3 rss_parser.py

            - name: Commit files
              id: commit_files
              if: always()
              run: |
                  git config --local user.email "aorumbayev@protonmail.com"
                  git config --local user.name "github-actions[bot]"

                  git config credential.helper "store --file=.git/credentials"
                  echo "https://${CUSTOM_GITHUB_TOKEN}:@github.com" > .git/credentials

                  if [[ -n $(git status --porcelain) ]]; then
                    git checkout main
                    git pull
                    git add -A
                    git commit -m "[no-tweet] refreshed episodes 🤖"
                    git push --force
                  else
                    echo "no changes - skipping commit"
                  fi

