name: Website Deployment
on:
    push:
        branches:
            - main
jobs:
    Website_Deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                access_token: ${{ secrets.GITHUB_TOKEN }}

            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Run linters
              run: npx awesome-lint

            - name: Copy latest README
              run: |
                cp README.md index.md

            - name: Push latest index.md
              uses: dmnemec/copy_file_to_another_repo_action@main
              env:
                 API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
              with:
                source_file: 'index.md'
                destination_repo: 'aorumbayev/awesome-algorand'
                destination_branch: 'gh-pages'
                user_email: 'millionalgos@pm.me'
                user_name: 'AwesomeAlgoBot'
                commit_message: '🤖 Updating website with latest content 📜'
            
            - uses: 8BitJonny/gh-get-current-pr@2.1.0
              id: PR
              
            - uses: Eomm/why-don-t-you-tweet@v1
              if: ${{ !github.event.repository.private }}
              with:
                # GitHub event payload
                # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release
                tweet-message: "⭐️ Check out ${{ steps.PR.outputs.pr_title }}. Head to awesomealgo.com to explore #awesome tools and platforms in #algorand ecosystem. ⚡️"
              env:
                # Get your tokens from https://developer.twitter.com/apps
                TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
                TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
                TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
                TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
