name: Website Deployment
on:
    pull_request:
        branches:
            - main
jobs:
    Website_Deployment:
        runs-on: ubuntu-latest
        steps:
            # - name: Cancel Previous Runs
            #   uses: styfle/cancel-workflow-action@0.9.1
            #   with:
            #     access_token: ${{ secrets.GITHUB_TOKEN }}

            # - uses: actions/checkout@v2
            #   with:
            #       fetch-depth: 0

            # - name: Run linters
            #   run: npx awesome-lint

            # - name: Copy latest README
            #   run: |
            #     cp README.md index.md

            # - name: Push latest index.md
            #   uses: dmnemec/copy_file_to_another_repo_action@main
            #   env:
            #      API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
            #   with:
            #     source_file: 'index.md'
            #     destination_repo: 'aorumbayev/awesome-algorand'
            #     destination_branch: 'gh-pages'
            #     user_email: 'millionalgos@pm.me'
            #     user_name: 'AwesomeAlgoBot'
            #     commit_message: '🤖 Updating website with latest content 📜'
    
            - uses: ethomson/send-tweet-action@v1
              with:
                status: "⭐️ Check out: ${{ github.event.pull_request.title }}. Head to awesomealgo.com to explore #awesome tools and platforms in #algorand ecosystem. ⚡️ "
                consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
                consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
                access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
                access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}